FROM python:3.6.5

RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2930ADAE8CAF5059EE73BB4B58712A2291FA4AD5 && \
    echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/3.6 main" | tee /etc/apt/sources.list.d/mongodb-org-3.6.list && \
    apt-get update && \
    apt-get install \
        mongodb-org-tools \
        unzip

COPY crimes.zip /tmp/crimes.zip
COPY app /app

WORKDIR /tmp
RUN unzip crimes.zip && mongoimport --host mongodb_database --port 27017 -d test -c crimes --type csv --file /tmp/Chicago_Crimes_2001_to_2004.csv --headerline && rm /tmp/crimes.zip

WORKDIR /app
RUN pip install -r requirements.txt

#RUN useradd -ms /bin/bash admin
#USER admin

CMD ["python", "app.py"]